"""
reports/html_report.py

Renders a reports.generator.ReportPayload into a single, self-contained
HTML document — no external stylesheets/scripts, so the output is equally
usable as a standalone download (GET /reports/{id}/export.html),
something opened straight from disk, or a starting point for a real PDF
renderer later (services.report_service.export_report_pdf's docstring
already calls out weasyprint as the natural next step — it renders HTML
to PDF, so this module is the piece that would feed it).

No template engine dependency (no jinja2 in requirements.txt) — plain
f-strings, with every piece of audit-derived text passed through
`html.escape` before it's interpolated, since findings/summaries can
originate from an AI provider or a crawled page and must never be
trusted as safe HTML.
"""

from __future__ import annotations

from html import escape
from typing import Iterable

from config.settings import settings
from reports.generator import ReportPayload

_SEVERITY_COLORS = {"critical": "#dc2626", "warning": "#d97706", "info": "#2563eb"}


def render_html_report(payload: ReportPayload) -> str:
    """Returns a complete standalone HTML document for one report."""
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{escape(settings.APP_NAME)} Report — {escape(payload.url)}</title>
<style>{_CSS}</style>
</head>
<body>
<main>
{_render_header(payload)}
{_render_summary(payload)}
{_render_score_grid(payload)}
{_render_business_impact(payload)}
{_render_action_plan(payload)}
{_render_findings(payload)}
{_render_footer(payload)}
</main>
</body>
</html>"""


def _render_header(payload: ReportPayload) -> str:
    return f"""<header>
  <h1>{escape(settings.APP_NAME)} — Website Audit Report</h1>
  <p class="meta"><strong>{escape(payload.url)}</strong> &middot; generated {escape(payload.generated_at)}</p>
  <div class="overall-score">{payload.overall}<span>/100 overall</span></div>
</header>"""


def _render_summary(payload: ReportPayload) -> str:
    if not payload.executive_summary:
        return ""
    return f"""<section>
  <h2>Executive Summary</h2>
  <p>{escape(payload.executive_summary)}</p>
</section>"""


def _render_score_grid(payload: ReportPayload) -> str:
    if not payload.score_grid:
        return ""
    rows = "\n".join(
        f'<tr><td>{escape(cell.label)}</td><td class="score">{cell.score}/100</td></tr>'
        for cell in payload.score_grid
    )
    return f"""<section>
  <h2>Score Breakdown</h2>
  <table>{rows}</table>
</section>"""


def _render_business_impact(payload: ReportPayload) -> str:
    if not payload.business_impact:
        return ""
    items = "\n".join(
        f"""<li>
      <span class="badge" style="background:{_SEVERITY_COLORS.get(item.get('severity', 'info'), '#2563eb')}">
        {escape(item.get('severity', 'info'))}
      </span>
      <strong>{escape(item.get('title', ''))}</strong>
      <span class="area">{escape(item.get('affected_area', ''))}</span>
      <p>{escape(item.get('impact', ''))}</p>
    </li>"""
        for item in payload.business_impact
    )
    return f"""<section>
  <h2>Business Impact</h2>
  <ul class="impact-list">{items}</ul>
</section>"""


def _render_action_plan(payload: ReportPayload) -> str:
    if not payload.action_plan:
        return ""
    horizons = (
        ("Quick Wins", payload.action_plan.quick_wins),
        ("Short Term", payload.action_plan.short_term),
        ("Long Term", payload.action_plan.long_term),
    )
    if not any(steps for _, steps in horizons):
        return ""

    sections = "\n".join(_render_action_horizon(title, steps) for title, steps in horizons if steps)
    return f"""<section>
  <h2>Action Plan</h2>
  {sections}
</section>"""


def _render_action_horizon(title: str, steps: Iterable[dict]) -> str:
    items = "\n".join(f"<li>{escape(step.get('step', ''))}</li>" for step in steps)
    return f"<h3>{escape(title)}</h3>\n<ol>{items}</ol>"


def _render_findings(payload: ReportPayload) -> str:
    if not payload.findings:
        return ""
    rows = "\n".join(
        f"""<li>
      <span class="badge" style="background:{_SEVERITY_COLORS.get(f.get('severity', 'info'), '#2563eb')}">
        {escape(f.get('severity', 'info'))}
      </span>
      <strong>{escape(f.get('title', ''))}</strong>
      <span class="module">{escape(f.get('module', ''))}</span>
      <p>{escape(f.get('description', ''))}</p>
    </li>"""
        for f in payload.findings
    )
    return f"""<section>
  <h2>All Findings</h2>
  <ul class="findings-list">{rows}</ul>
</section>"""


def _render_footer(payload: ReportPayload) -> str:
    share = f'<p><a href="{escape(payload.share_url)}">View live report</a></p>' if payload.share_url else ""
    return f"""<footer>
  {share}
  <p class="disclaimer">Generated by {escape(settings.APP_NAME)}. Audit #{payload.audit_id}.</p>
</footer>"""


_CSS = """
  :root { color-scheme: light; }
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
         margin: 0; padding: 2.5rem; background: #f8fafc; color: #0f172a; }
  main { max-width: 840px; margin: 0 auto; background: #fff; border-radius: 12px;
         padding: 2.5rem; box-shadow: 0 1px 3px rgba(0,0,0,0.08); }
  header { border-bottom: 1px solid #e2e8f0; padding-bottom: 1.5rem; margin-bottom: 1.5rem; }
  h1 { font-size: 1.5rem; margin: 0 0 0.5rem; }
  .meta { color: #64748b; margin: 0 0 1rem; }
  .overall-score { font-size: 2.5rem; font-weight: 700; color: #0f172a; }
  .overall-score span { font-size: 1rem; font-weight: 400; color: #64748b; }
  section { margin: 2rem 0; }
  h2 { font-size: 1.15rem; border-bottom: 1px solid #e2e8f0; padding-bottom: 0.5rem; }
  h3 { font-size: 1rem; margin-top: 1.25rem; }
  table { width: 100%; border-collapse: collapse; }
  table td { padding: 0.5rem 0; border-bottom: 1px solid #f1f5f9; }
  table td.score { text-align: right; font-weight: 600; }
  ul.impact-list, ul.findings-list { list-style: none; margin: 0; padding: 0; }
  ul.impact-list li, ul.findings-list li { padding: 0.85rem 0; border-bottom: 1px solid #f1f5f9; }
  .badge { display: inline-block; color: #fff; font-size: 0.7rem; font-weight: 600;
           text-transform: uppercase; padding: 0.15rem 0.5rem; border-radius: 999px; margin-right: 0.5rem; }
  .module, .area { color: #64748b; font-size: 0.8rem; margin-left: 0.5rem; }
  p { line-height: 1.5; margin: 0.35rem 0 0; }
  ol { padding-left: 1.25rem; line-height: 1.6; }
  footer { margin-top: 2.5rem; border-top: 1px solid #e2e8f0; padding-top: 1rem;
           color: #94a3b8; font-size: 0.8rem; }
"""
